/* Auto-Generated by ChatGPT */

#ifndef INTERFACEJACK_H
#define INTERFACEJACK_H

#include <QObject>
#include <QDebug>
#include <jack/jack.h>
#include <jack/midiport.h>
#include <vector>
#include <mutex>

#include "interface_audio.h"

// Simple MIDI ring buffer for queued events
struct MidiEvent {
    int port;
    int channel;
    int type;      // 0=noteon, 1=noteoff, 2=cc, 3=pgm, etc.
    int data1;     // note number or controller number or program
    int data2;     // velocity or value
};

class InterfaceJack : public InterfaceAudio
{
    Q_OBJECT
public:
    explicit InterfaceJack(int id = 0, InterfaceAudio *parent = nullptr);
    ~InterfaceJack();
    
    void createNewPort(QString label) override;
    
    void keyPressEvent(int port, int channel, int midicode, int velocity) override;
    void keyReleaseEvent(int port, int channel, int midicode, int velocity) override;
    void keyPanicEvent(int port, int channel) override;
    void keyStopAllEvent(int port, int channel) override;
    void keyPitchbendEvent(int port, int channel, int pitch) override;
    void keySustainEvent(int port, int channel, bool pressed) override;
    void keySostenutoEvent(int port, int channel, bool pressed) override;
    void keySoftEvent(int port, int channel, bool pressed) override;
    void setProgramChangeEvent(int port, int channel, int program, int bank) override;
    void setVolumeChangeEvent(int port, int channel, int volume) override;
    void setPanChangeEvent(int port, int channel, int value) override;
    void setPortamentoChanged(int port, int channel, int value) override;
    void setAttackChanged(int port, int channel, int value) override;
    void setReleaseChanged(int port, int channel, int value) override;
    void setTremoloChanged(int port, int channel, int value) override;
    
private:
    jack_client_t *client;
    std::vector<jack_port_t*> outputPorts;
    
    std::vector<MidiEvent> ringBuffer;
    std::mutex bufferMutex;
    
    void pushEvent(const MidiEvent &event);
    void processRingBuffer(jack_nframes_t nframes);
    
    static int jackCallback(jack_nframes_t nframes, void *arg);
};

#endif // INTERFACEJACK_H
