/* Auto-Generated by ChatGPT */

#ifndef INTERFACEJACK_H
#define INTERFACEJACK_H

#include <QObject>
#include <QDebug>
#include <jack/jack.h>
#include <jack/ringbuffer.h>
#include <jack/midiport.h>

#include "interface_audio.h"

// Simple MIDI ring buffer for queued events
#pragma pack(push, 1)
struct MidiEvent {
    enum EventType : uint8_t {
        NOTE_ON     = 0,
        NOTE_OFF    = 1,
        CC          = 2,
        PROGRAM     = 3,
        PITCH_BEND  = 4
    };
    
    int port;
    int channel;
    EventType type;  // Use the enum now
    uint8_t data1;   // note number, controller number, or LSB
    uint8_t data2;   // velocity, value, or MSB
};
#pragma pack(pop)


class InterfaceJack : public InterfaceAudio
{
    Q_OBJECT
public:
    explicit InterfaceJack(int id = 0, InterfaceAudio *parent = nullptr);
    ~InterfaceJack();
    
    void createNewPort(QString label) override;
    
    void keyPressEvent(int port, int channel, uint8_t midicode, uint8_t velocity) override;
    void keyReleaseEvent(int port, int channel, uint8_t midicode, uint8_t velocity) override;
    void keyPanicEvent(int port, int channel) override;
    void keyStopAllEvent(int port, int channel) override;
    void keyPitchbendEvent(int port, int channel, int pitch) override;
    void keySustainEvent(int port, int channel, bool pressed) override;
    void keySostenutoEvent(int port, int channel, bool pressed) override;
    void keySoftEvent(int port, int channel, bool pressed) override;
    void setProgramChangeEvent(int port, int channel, uint8_t program, int bank) override;
    void setControlChangeEvent(int port, int channel, uint8_t cc, uint8_t value) override;
    void setVolumeChangeEvent(int port, int channel, uint8_t volume) override;
    void setPanChangeEvent(int port, int channel, uint8_t value) override;
    void setPortamentoChanged(int port, int channel, uint8_t value) override;
    void setAttackChanged(int port, int channel, uint8_t value) override;
    void setReleaseChanged(int port, int channel, uint8_t value) override;
    void setTremoloChanged(int port, int channel, uint8_t value) override;
    
private:
    jack_client_t *client;
    std::vector<jack_port_t*> outputPorts;
    
    jack_ringbuffer_t* ringBuffer = nullptr;
    
    void pushEvent(const MidiEvent &event);
    void processRingBuffer(jack_nframes_t nframes);
    
    static int jackCallback(jack_nframes_t nframes, void *arg);
    
    static constexpr uint8_t MIDI_ON  = 127;
    static constexpr uint8_t MIDI_OFF = 0;
};

#endif // INTERFACEJACK_H
